core:
  alerter:
    delay: 0
  metrics:
    apm_server:
      server_url: http://apm_server:8200/
    elasticsearch:
      hosts: [elasticsearch]
    kibana:
      host: kibana
    redis:
      host: redis
  redis:
    nonpersistent:
      host: redis
    persistent:
      host: redis
      port: 6379

datastore:
  elasticsearch:
    nodes: [elasticsearch]
  hosts: [elasticsearch]

filestore:
  cache: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@minio:9000?s3_bucket=al-cache&use_ssl=False"]
  storage: ["s3://al_storage_key:Ch@ngeTh!sPa33w0rd@minio:9000?s3_bucket=al-storage&use_ssl=False"]

logging:
  log_to_console: true
  log_to_file: false
  log_to_syslog: false