name: unittests

on: [push]

jobs:
  build:

    runs-on: ubuntu-latest
    timeout-minutes: 4
    strategy:
      matrix:
        container: ["python:3.7", "python:3.8"]
    container: ${{ matrix.container }}
    services:
      redis:
        image: redis
        ports:
        - 6379:6379
        options: --entrypoint redis-server
      elasticsearch:
        image: sgaroncse/elasticsearch:7.6.0
        env:
          ES_JAVA_OPTS: "-Xms256m -Xmx512m"
          DISCOVERY_TYPE: 'single-node'

    steps:
    - uses: actions/checkout@v1
    - name: Set up linux pip cache
      uses: actions/cache@v1
      if: startsWith(runner.os, 'Linux')
      with:
        path: ~/.cache/pip
        key: ${{ runner.os }}-pip-${{ hashFiles('**/setup.py') }}
        restore-keys: |
          ${{ runner.os }}-pip-
    - name: Setup Packages
      run: |
        mkdir -p /etc/assemblyline/
        mkdir -p /var/cache/assemblyline/
        cp test/bitbucket/config.yml /etc/assemblyline
        cat /etc/assemblyline/config.yml
        apt update
        apt install -y build-essential libffi-dev libfuzzy-dev python3-dev
        pip install --no-cache-dir -U pip cython setuptools
        pip install --no-cache-dir -e . -r test/requirements.txt
    - name: Test with pytest
      run: pytest -rsx -vv